language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: V0ktPeM+cto4/USxHkIBWPyyZ/ni5v7yPwGFVbalPUvkPmYRgFq5T0p8E/Tp9iW1JXVJ7x7vigytwrxjgChgcI6pU7ba7ud6qpbV1XiPnR7KTDi9UJ6/R4QyZkAyTewprGiPCMNgFm2fpweA/+emII+QfKvLvk1EQ5mnwJa2urbHZpxZUXoT9F1NtGoHxXCwGHS3XzGJeB5wSHj9/N3JhQ1gljgPGVJYqJ64pFidTyNH1I0hCekmODUwXiq+EGtPDd3qitnW+cAyjkTo38t4VMiGfYnnJeHE0DUPw1T5iKxUlJbuMNqbznnbNZ4UA5Yl1V7JRvqBX6IHG/Bz2Oqz0BdeTRujhJsHvTYxrwRjujA3lboe/rCJw+o7I18ObO2U3h7VGoyk93S4b5mgKg7xYxnmiW2LzCDq+XTo2/+SaL+IQD74A4YwQit0Ng4xKCwUveT2hIHkzoTox89plHNtU0f30BAbAz4WsWlvn/WNcuXwjS8It2mmUb0P5DgQnBX+FsCfQDfUl7dDulFZc3yrYsPnfJGkQgLYJ2YvgiUkZSMwT9gNj5RlUucuEMh/ZnL/MQqo3jflSTu0Llro0znXYcrqqd6pT2RjQ4Vx7UTktNRRBnSAERwPPA6E8LDdajLrdYHDBnffo7cCG8I6VlNEr5IM+fwhlJ/jgr7Y4DFN464=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
    secure: FExNbWN7ZnkrceVIrvZisk0kuXEQeAk8HipOsIBmaT3L+nVvNWGpAiqHIIzOmc0qcxe7MDSMs1a91yIWTqPDddv8o602xVOFTi0a3SiJEiyMFwc5deOTeBfQjYimxIb3bUqD8P++cdgrE0XBZXK5NCHgtgvviF36iTKaKI7+2esTlxHPzqh+TYuMxm5qwb0isXMXRAI22G2WeKCsqMUgrT7ei8h8YUsS4zTHq0/v4Fct0+uPc3X86UVeCSJx3hY9IKsPn8afbepDP+9eqWl9onVc8G4QAY47bNL/d7A/sHyGum5Y7Cf/2zj9r60V4OQSzGqIZ7/180aQj9o0DprZJ5aOHsGV+BcgAKmpdFccO/6eALuqqntzYIRMYntO/NoIINgf3jRLSYrOUUiWzu9Egdpvzg5+u/NPar1t2TYKyIj8SDTrNMz6uJqcvpfc8eZnOH/5xeFOJHbOn1SBeDo4584acKMiktj4QHiD/HGycZdFzhXTJ171Vms0bAaDl0sI22waVqd6x1HhovzRIilu2yofBFCdXqSBICKs7U1pa42WU3gfNfd+P2WLxWZv49LKJ7AiiuxFCQHFOJpTR84YbFko2iP1EiwOoxygB/3ZWjWI7mKzUukZ0uU2knlwWnxkJhX2KeiigahOk52FhPuJnWT8edHAXY40VIoxw1oMlK4=
    secure: IVeIZl58iVjnH45NjHlFzlDdtmzpZPdtwsU8/rKE3/xbIVrFhfkXLHN+7++dIHB7rXGQ9CoLItzGecUseNSqezdoa8cOH2DmpowE0WPiSDExte5Gu/iJjGOe53GiFQWhCyUE2sdEgeoxtYBtqU8+7YUTm+LYX3Liqw9EaaUHQb6JMuZDzxoNXSFIRO7cr5bclI4OxUhJathg7Gfqvh8Me6UsnbfeIqdPljDU1wqPgyDNSQs5myvrqyxl6PBBIVGV7Rsjh9S9OkqEkOCjtBu7YWRe/VCox+r2GISPbVlgYBAUnnlQqGH+2+y79IfYn2FJVoMROHgw4ww1Tm6b6QGKTc+U8tYAuzt5ihwnHppzbqO4t//U76Iyc+UtAmRKgXnELqjzP1zgSXewrITOaT4FL1hy4SgXS1kmlixPbN+6R5XCbPZVl1sR6pcj+PCu3fx6wHz3/UFUFLYu7qr0lzfEFUKFICClqrpGdoM2A9Y/ZMNKXIlqhO88lncVikqy/z4tOWvEOQs78UCAz1dkVEfBY3Gl0sXYruCy2ibhBSGf3lVe03Pxa+DrpqXWaBPUmdvkw6CN1VNwAthQwi5vZ9kTnWzLV6AGKzoCVXzctq1q/BjarUB2G/IcnWbou00BO8L7AZLMSfHQCGNtTi6wvi6dGX2FEN2gKZKOVOJBWeunZ7s=
    secure: BQyuclmVMVx/ILMkv+EYkhF8ItGMSfY5ybZHegBT7kNTninlRgwF74K+n3BdflZ6qKpRc/kirWPlLW6rrieOGvdriexhuYcP5hUJ+E5YW4/XYoSLiKn8IbKdwfyvQpax4/jW2K2T/F1SsT0ozZ/rIZ0imVTnPEuH8ToOz2H5dOkw2R8U6tTq04yqVR9uLxTM7VJh6+3p3Wcvu4VsK1uD5E0rlQs9qKozdfe1nnoEemDFbuuCK9NbtB0O/u+hIlGcoO2ofDCYjOoA/D+RAU+FZGjCbza1+++8Cpvwtn8ZKfKXSvFzn0ZmX1yWgF992uH7GuBmhKobitj7jluuUBqzmEh+nMe275TJz9Tsd+4C5AWgRRPhuKXQihs0q505qxbqsVvCYpvrezIMNrk4Rk2aV4FbKvIaFjf6MD0VgElhl92LViQfch4Sua4dOkhRa5ba5BPvDr1+HDHjO4pPGL5TTtZ1HT1pQaiuXQ/CC+mV2AqIqK95xVojzGf11gW+vacccCUx+CWYuoc/Gc9AnDqg2ckLD9aCa3sTSvwDjWO2RnNvWpUkLz52R5+2JItujGGp69dgiAnEAn1/jVrPdWICoybv6GF1YlRnTR+p2FmSScB20g/Ys5udLTDrJC/0RQ+q/LGLi5kK/wJCg9fKKvzfuXh8iy16VyWXOypHl0OIUdY=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build and publish to Docker Hub
    env: GCP_ENV=re7
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and publish to Docker Hub
  if: branch = master
