language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: L3/IgdSmP7SLV5zwHqXievCeeH1eNa9QHgIHz20bo2/RcE9nZpADTG52ZYwA29KpmxBeE6KlwTFvM9OK5Rg/ZhKMc+A3oTYMbBpWbOicZxS/nUXKNfxywdlKmOs2wce/bR524DoTsE8Rg0723tLMEqwRxw2Q5pgg6YPiF8xS/xCVqVAaYHpoil9YDyDfgNMSJJI02I7y4ETyVph0dlHKRdnBRrDjIOfVOa6udyiIhDyiKQr7TVxkhF3fwXwH5/WbqS5eaV4FTvvkeizWitRTNtbG7pgB2ikIqFOn7Fp+8XQrcHNPawTb2ozgbdeyF4Ks3NHw0U32JE9+w36eWiLhehbrZRgu1jSsjj4pvuzmyt8QvAvJUOwp2Y+PzeuFENnPf+fJUMH25rrul45aDbgIOcreEKQWmLM121GczEyLRWan4xl7UeanQrKDv85QqAYiYaCtY//9StKRWPOi5qfshjxd1yAAAefSG8UqCrwdbqKAwjcOFmEERibqUQbwLxtR127fUhzvtodQbSljN5knQ1/nHtX1iR/TK8dhRYRP0HZvwlr+ORk3ZH3tMc0ro6vA3Wqwizw0zXitygyXxU5yok+6K7YYzzehoOINVvFeK2TKl8GvLfIhw1bMug0Tr1ClJCQdU9B7R1x43nIicYw68ClOKbSIDUqPhFyRg3f8ceQ=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global: 
    secure: gUpLWD7fP5shJtkrvRW7hWLXN88AAo6nRnEY8ff4G+q2EzfUig6v30dv8wDuKHrvJ6riEuj/++uTm7yv0G0Hpol9zypNKWM+em1mK9nOK9dLSsrQDOgTQ+wNtz1BlrOpfUSKC38EzkBJLSYAzwuQhugzedDvbmbd7sS6ie7XX2mqyIcRXOgzhFVQU7RSYxTtY00y24ja5HI16L+AWaDwchEurAcEoV8CjfThUCEq2llKIV8UK5alOQjWNSCvkCawjb3sPRzEKSBTYv1qsq6jJ/WY7xvmKJzGHq033sH34liewLjhT0fbzLivgvandOqJA+Yz+MiRvKfeXI6PM8MyQF+LH/7lfXE0N+1dLpgSmu+WlLfKLFkMy/+Chk2VBYZTuVi5lmn8oYD27Ik7yhl7yNVFqwuF0J8n3QzP5pBO+eiaxQiCu3YLYP+Tgoe/FRIOYTCVr7ZLhS/fAXben8+95o4WMXz1DhlQd7erAa9xv7yh8y2u5jvsNwRqJzbS+DvsuDHeQYu0/CfWAoECDzocbgeXyVxgcSAECczlMb1rKOeBiVPeFLEQa0v6BsaxtmDrp3O8Gl/yDHTeUeLaTLPjxryqOVkbWJ+/yENsfbu8eX+uf3vM0tsCpwtSfyR6Pu13Eu2LeEuicgI/wfHxkXo0MmIWlF5zLIV/sb/Lk5EV7W4=
    secure: R4XoPVyGD3OJfCekxHY38FoYb9Zl9o1UsRT/uNN0gEcQSKYmyXJgKG9USe3V85rIbrz6/TnVv2v5PON7mYGX7VZ2wzu/ohCi06PDHZQnwQde/oND/17hcGnLIOZ5NsnuQ8GWQcqkX/fJNxDtHlqLMkMxQeTGUUeUv+3PbgXmJVdLqoEcZvrdRpOq0TSjmXzbam0JpnVvDZ0QsL5wJ5dIC439uXNWhI/ajnaZyzpAmESlf0iL/5V6cdOARJXhWePQ4EqwnENJ2yKSHCk9gUbu4/YlGrU8IxPhQBjJ0jcs2J74qug3wKMMsyvs/Vp8HAo+6lFsZKRZ4/P8rWOW2m+mWw0PYWQaR5ZVCF/sOYLm8NoSKr8t9ao39RGU1ZloUJUh4gi0aSwpeF0j1XvHU6AKESWgUocsL1KWAgHDkR4/nI7bZHlX0vJJAbbkg9XtAMuoTFUPfqknU+U941kGwdGAwbP6idKEzdQS4PMAeFLVVqvUCaXVC0avFElaSkbaS9noiZRnQpBgBVfHTvtdKsx6kmDJZiORIjdAoIzcqeAPIS59wW78aNUrOQ+c8AQRbEnja6A6wPE4LcAclFQLkh/AUYAs7pfRI1ZnE+2HfZsJLecUJ/BIRcYcceaS3v/Mj5cSbup9azb2Lo3+CiwEbrmpmQw4Xv2BWS6cOGMpgLb5roc=
    secure: fCg9WBdJjMKmq3f6wR46qMfrFWIi+rllOY1VEvY/Pu1/hG2vUOCwtENJWLGxtN9jjlfhqfBOfLZImFTFPqhLAWqH3s3iDcPbHaYane10BaH9RhrZO+BHFyFBnYulIQ69IGym3WhsGaVvQ1KsFNUvj1XnOx8b2k0Uk1p6JaVnPKXFq1cDyaCRXw7wrbN8TbaEFkcbKrJHw+LNeaCcpkPKfHWUZRbgG5zTf3ugruFtWkc2JZFE6mEqfi4t/TAGu4eB6tROOcg2W5/NghBqlUqnh38DkDRxJCZVoLtsAjpl2iE8mvNDZbf07dk5qAD/LIXKDKDlycuma6/Gy+403PV8oruvRIja7PKr+/9PHbHUKh9ZBgljXCjjnmVBWvR+GXnPtuDBhsQ6h01dhE1n+mPhzExL8+dH9x5BWthp6DkaNgCrYnvoJoJaQc5PzwgBLAHfbhc3ihISjMq2sTL6rtNigkSOpqVkg98CsIxnB2dzF6cZUj/LM4mbCZAt+/94k/hhp5/TVihkRdQhlkekIj6W7QUxF1vOBttATrDA5HUsBNsYppowoV5kjTneZRuA/Cy1OXsp31DRF1qlgmdXURIbBwzmUmo+eqKNiDxPsKIcMzpdgBAYSh+PQeuR9RtfOoHmipOif+AqzdLGt5piE9fPF9glZG4rSVlWMY6/Aqt9P/A=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build and publish to Docker Hub
    env: GCP_ENV=re7
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and publish to Docker Hub
  if: branch = master
