language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk: openjdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: g2CKr6/9ogKJS+raJM+KPtFAPjI9ToBlw+1sTTzsH+0ytpXZjegCp35i4+/B2MvMxkl8H1V+oa5QfAczhKNJ4U48t9DhibOchFrr8lgU9liH4G5bF4u8/mpBmU+0CgRbdT9SPiexlqOVKnXHeNXusV6mjxMM/S+0NF83MbtGBURmEItixQiC+91Dt894aCDX5qxm3Dpq5vBnlzQ95/rZyzLjtzJs8mZAWhoBaZNTXJng6dkTbP24QLuDyCynxY4Nz6SBbDhEZTsBbGKsnZ3Z5Grq83GachEDFudNJMV28YQwkq+7kCDqs76ndGCQnjkIIQqosMluh1xMeLSmvx4nGgdYmGOhc9pCPLJS+6/cPtiNsd10TdgIBxVPe7ApTSyDundYVGtG0RQRuHbIqValPW+GtcCGP23gkt3oAfLQIX+qhhN95eegopnJNyNQ0sOC9NTYU1yXy01XCqKJg2IsTQcR/Drv7Q6K8jCCX3Gmqn70ZBGw8/Tivm6eivKXJbbPP7Ix1LnJJzuw7abqGq/Nxtus3o9SyD9fm3WJS3pAqhHgarXd2Iod8kImwC+TDSMMBzDbzgACrKWvvI3K3WRvjvOOia4VpCXYM3Ctp8FlyRqmexwB0gZ2ceUJ1Sab4RNDPx1xEGqmJl/Zgz7cXuX3Auy6M1SJZCz2LtdmjGHf37I=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: HFROY4SP1F0aNHpzFN/icMdr80tz/fuWRHNPLgdlRqL/FB7iMCGE3w3kuewHS5qfqhqdZHze5+226aRVA5UFBNwDJiWef5myptosgQBnQ3z26xLFBvhtHk8Kk/AH60jfKApTHCH6wPKDq4S+Lpo42LygzGOojiJIbry2x72kF0GwaP1zPyIzRUBnhI8y6xRas8rQgvrdpOgRQkCK0evXCbzLRtAGlspPeWeF0W9RU2+poOD0l8eY3cCv88bCMsHtLCgu/gSiYEmjUECYQMDfXX/VA1+3ZkDH7ELJD6qESyhfgUAO8yt5hTzvDX/J4qHJHsVfNWIEmtE14l1peWgC7yZMoEFTq8eE0NvoKYwtvjUONmux7z7HVUSn26fiuRkWHpQtFu02SoZY35cE+nHmLaOfsV8TCGgqAGKtEzmiIKs/Skl9kRHQYIq4nLsGI1sts68osh5DMcNo6NRL82XxH1ocJxif6TQl8CAY0NyOc4f0hxIAjrnf0YFXRtlvsL6QeHs8/6Q9ADENxOPhawXfXeS013gxCf3mHECjT8jhSmxrAUBSRyGva9U/IasifqFsphA6LxStn+OtT896GiH9pZGPBG7Npp8gz9pWL5JN2trNNrNCrKaum5iwtJ7CMKNURpImfTvmVUY0e9lACytbw6lI5SHylkO7jQZi8MdyMrQ=
  - secure: a+ANp54rPBIQnGJ+ssmVLAeE/zaIBQ9b/MeE+htlc+JNrnVcRjVzvVwUtPG+rJ4LBllapEnSzy9gA8XO/zZvRrz6hzX73WS8MHhzcEa8R7nbRE3gqGMYEBZupCwBuQqe72aIgVTYEmm3c2OGLM9x7E50pXpEJ3Nm9/4UajFqPOJvdCZLKypF3VXiQfKdvE5Tfh42QNbbKgZU7XWz9gvObKx9RDuQQiyyfrPwZ1GFK19kDWksBP0dJGaUU+++lAs8hf5plOTHBBFlmSiET24Pb+sILmgC2yKSlUhxEwJkCsM17749ly1ec7JeJxG+O80gJIeQt2/VGrISPm7S6TrT6N3sbThSV95AZojBcVjIvFMTAERDBuuhC1GZRBlJWuatsfAJMgDqrzipaVFVYTw2lbGyGrv8lSRECbq/QA/49wuya4B7DEGBFLLPt3efDs3JtjWhwYXlv+8xIxlR0JTi7CSuCvXmvTxVQkppR4dnuBcXAxki1CjGOmx7bxoOJHx3j8ahmc6NOgsjKOC4goiqQxHHnkedRf8k675xGweFYzQlXZ+A/cFqvABsy3CN99bIEyEoHCdLttWto0bsPoVkIkz/SfUHSa45S3VbeKdiFUwjS6G/OEJN8BfmyciR63U9C0Wr7jA9E+qs6Jv8i9xh4rwjbKyl6zLwcY1tDEJ1Y2c=
  - secure: kurE1tEfYkri91M9h6CR6nIZktRjh8etsHXcn6tyxTKKQByQLANxPO5kktAo+S5Txewlopbrj9ygrVnBpmohUGJpixrZmK+rghhaL7H49f+FMbeAUCJafhnot2E52w54J/8GGBoyWBVHlWxhqvHUpV9MW3Q16gdR2y79Uv41joo6TN2ZXOimfUWCzqv2/NU8FRxY1wDfcHwnLIptX/nSnqZajXeCQi+Dov0rm9P41w41lwytJk8rtxP2xtprfTzQnAJZguFDppMLMXj2hsYbPLdPm235x7GhIGsXQnNhQUF4Gh9Di+DE2dSopUwGDvEuqHOTYpJ1TCWFsO6EEssgfhT19/OoeeeM9UTk+QCBPXNqM7DixACDN3kqRAa6ST0UNe+7LCyPqfq2B2Ou7ZTSjSxe9CO6gZLgxrFOjBozUqp5tAnVLlad4RhACBWRm059UlKW+6fhoBkhSaM2YSEhQ34GfSY46n4Lxg1RKl/dAaC17pQPaQqOHOtl84rMJOJPMpE+Xv43eZWtV6elKIHx5xV5L0AXIOhSYFV2ZABc3qgkyd+t1JG71thc2LLqjTM4gvL1TerYjLywfMNz0Bs56Tqrt2ngHRzhqKvUV4aCT8ASx15M8EbQALVJxowkEKgSUrzz9KUCZNzMj/GUUyp8JxxbF2nsTc9tvoul2dbvPsg=
before_install:
- sudo cat /proc/meminfo
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- chmod +x mvnw
jobs:
  include:
  - stage: build and publish to Docker Hub
    script:
    - travis_wait 15 ./mvnw package -Pnative -Dnative-image.docker-build=true -Dquarkus.profile=local
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and publish to Docker Hub
  if: branch = bare-metal
