language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: M1nLdH2mmRd8lBI0zaas8rOZ8GdfH01ErrkP702Fr0PB+aztdivcRum/HuGuvQRdBvSk9ZvuJ16JzfMT4OdzFhBTT7KozptMVmMILTWbhc57iYJlOOFYO5gXMEXKy9qGi/xHlc3VMwXGfCJScyZtOUV5ilXjQ7XelPHtDtyYrYOuoAIbghcE2+nMmcPSuVFdMhBEddAQC0vRjT6EKVfwwDkBpnOwcEBKK4A7gpFczL+Q0umd+pR/WTyIyRoekGL7eUzghRJAzHvmHRfuHRVvg0oKKU/8nYFXhI2rIIut48oHTBibaOcXFRLzKd+j4kyJcEwApPYyuCJgrVPsnvRvG81vG4Kl+6jEhBYR86jX3HPH5xGXXP9JEjfeBuHFZGjT+BPa5CQMoAECxVDN/b8M3+YDUIeI3xmhii6fQEH/NDkuG8QVQ0zO1BVN/R1WBhyFk71HkzKkQlJnkN6XwY96HayEqP/O3umnzpjqrr+gOb0s3PAQvnyzQQS5myTlkBGZPv3mrcMDVFmsxRu906BT1RbD6JmO4aNktz8UQFifE6ONSsZxMAwlzdr1avAjmS5bsZCwY9AgV94EEvT9ZDtQnZRR4mWNM9NpHJaRCCKozKTJeUY3L+Om0eQlELXmBgeI4t9DRwS1fv64bUWieEVIfn86CzNeHq4xqVjk5lWQDww=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: rWXm1fYQMPJb2YFV7fF6V1xzdo1kvk2QFhfqJojoAZFEJRGGQbUBWwwiawE/kcGz9z6PCLwk5bwImNMgGhkFLKFi/IJjttnfM9wwG7WD4wwoBV7MEfBHwT+ZSVkI9+UxcerFCuda1mzZh8alyTkxkHihy3VKOM31czWuohG3ae1UL0LzdDngQhS26YqwmiyD6fVbnQxL+Odmz+8ybMJT5dT0n/wpejg96WuZ87INW6jmhgxgTHaNYDGOY4y6JoLTzVANwJwncDXWs/nCFlm29Gv60hO4OhHNVZWPgCzJGeUUPn64HgYuTQ2/NAyk/d9mYAw4zSeVxx2CeaWf46E5ZRtnnWxoxKeAW5E+iwodaMqSqlN/DSYckHQvwNHgeEOH3pJiJKjETwTVK5KBrbqazkjS0jNoJ0gC7Wzu98fI8wuJ6pfDj9fD1NyYc7iZczra0Q5RxJxAE2MVjxgwvrYd+ssrycIXgskTQrUAs7li6nqXLWKLgNVr9g5zy0IERCRgpDo3r4Y3c34uWVZlTs10jWbaSTp9vtqWUdVoagxGDB7xQu4gWdaVdDH4ydipxjRcQoqY1Ouf09YwosukBKA76tCF+X+jWaZvWy87cyQ1kEEdrnMjbKfIAs4HFEJnZ34vmMZQAFSm3uloBByfQz+fLbd08ZZZWgt9/jaPQoAyZ9Q=
  - secure: prw44JnyFZISv/9BpFZZV/oi3aypjliHXpKE6fidaLKLJVlgLrUzgwdcHu2BuyTSYRVXKH1yhIMex8pez2DEpFkBIXN9nMbHOA83MfGaDgN+VeAVDvM8z/CsY3AaBDB2JAT7g3vNZAQCnKIFrcsJ5CZO1MuOrfh5lAJfs+lr1YryHwS0+McsKKLrxARVZ63w2FgcVwzKOeFvELCtW8qO5nRDMPgHr23Cl34hg0fgDjwEUfe9MzJVELppcDzu6UNLvYzfKAw5ItsEBlDEWAno6lzo/VuyCu2TwiFfw04lbTN4yV6UZ3Y/JQC0XwTBMsN41YJY/5FUaNI+hM1KOnNt9XsewlEBzj+y3TKXN6iirc7BhuZAe3y8tl5ypmDAJ3bbPO65FASv64Uj9WUQ+JI6fTuzd0dP5fJa2/7eXtIYQF3huCQtoVq2r+CD9BzD5qMVCL+JeSETLSXjtvUsPrMiXeA8LhMtkQ+sEwCuOIqDPCH8DbI7vCk/cwxgN0cQw3TXRIpe4yc3cKsyC6NMp9Y4znEJYhzHaKxfxqp8ZM1fUG/evbzX6rLHYUA9gDxzsjtGRaCDgOPkaO2CFyIItoqqVi7K0Zl6o4op7y/K9pUf1lltliMWOTG/Xe2JMfUWIVUviw5vsaE+07btwqKRmQicAS3lV5vm96V/xvlSsJNrOps=
  - secure: Y4QwIs3YcJYMZUMcwiYZzKhKJbbfBOFtEXhdhEhcD9ahAMhKugFZB2UKZTJvAOeAZPPMFU029TYwDqSS8GwAEXvKT/V0+/jhNGTnE1UdYJypSeY7U0od7YEU5O+d2FCR+m0alnwoz6gOm+PrAnfyRpgVBrMejo7UBg3Jg4yx93tEX7cwJE+zr6FqOayEkzX2St84LnFHX29ncNEJMTnyfHd9udIUblE77Fq7l2xJ1TTOwS2baGF088pNVbSEDEARGNI7K2kWblUzoaPhx/XHEGF7hPBpVccbgcMGviQUhWv4Oi3IQb7byBu+xGfgY9M9RWPep7hzMOvdW/LJYxOAFXL1DbHIORV3jMncvF4+5dWlU/wuEssLAn7iiEdRdMqIQKyLLKWUZsn76v3BCqsLBwy+yGm9K+17ysxI0C5ivlX0apcGZjuXh2luadsiSGmQFHItZqwNcC66nSvN/XjefcWOaVo3xm5BJEdmco8mJ0Vy5c182Tm06ePjn6EOu2Ni6T8qKJG4xebXPNL5MF7fkinLLy7qPkPynZLvybRkU915mOx+y3RbdcgKJPNJw2i7Tft9V5yOjObWrAfxEc8/rJx4y+9EgAOLhVEYlepECAy0B86KZk3TFKPgsUc7EdXFFSB8zE16bFBI9ouyxetS9fvlauuszmncnsDdN7ieRkw=

before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
#- travis version
- chmod +x mvnw
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER

jobs:
  include:
  - stage: build and publish to Docker Hub
    env: GCP_ENV=re7
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
#    - /bin/bash scripts/travis/deploy_to_gcp.sh
stages:
  - name: build and publish to Docker Hub
    if: branch = master
