language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk: openjdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: g2CKr6/9ogKJS+raJM+KPtFAPjI9ToBlw+1sTTzsH+0ytpXZjegCp35i4+/B2MvMxkl8H1V+oa5QfAczhKNJ4U48t9DhibOchFrr8lgU9liH4G5bF4u8/mpBmU+0CgRbdT9SPiexlqOVKnXHeNXusV6mjxMM/S+0NF83MbtGBURmEItixQiC+91Dt894aCDX5qxm3Dpq5vBnlzQ95/rZyzLjtzJs8mZAWhoBaZNTXJng6dkTbP24QLuDyCynxY4Nz6SBbDhEZTsBbGKsnZ3Z5Grq83GachEDFudNJMV28YQwkq+7kCDqs76ndGCQnjkIIQqosMluh1xMeLSmvx4nGgdYmGOhc9pCPLJS+6/cPtiNsd10TdgIBxVPe7ApTSyDundYVGtG0RQRuHbIqValPW+GtcCGP23gkt3oAfLQIX+qhhN95eegopnJNyNQ0sOC9NTYU1yXy01XCqKJg2IsTQcR/Drv7Q6K8jCCX3Gmqn70ZBGw8/Tivm6eivKXJbbPP7Ix1LnJJzuw7abqGq/Nxtus3o9SyD9fm3WJS3pAqhHgarXd2Iod8kImwC+TDSMMBzDbzgACrKWvvI3K3WRvjvOOia4VpCXYM3Ctp8FlyRqmexwB0gZ2ceUJ1Sab4RNDPx1xEGqmJl/Zgz7cXuX3Auy6M1SJZCz2LtdmjGHf37I=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
before_install:
- sudo cat /proc/meminfo
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- chmod +x mvnw
jobs:
  include:
  - stage: build and publish to Docker Hub
    script:
    - travis_wait 15 ./mvnw package -Pnative -Dnative-image.docker-build=true -Dquarkus.profile=local
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and publish to Docker Hub
  if: branch = featBareMetal
env:
  global:
  - secure: b2ZZPkUdYw9tIVoTxXQ/366uDe6yjpQcrmNnGgzLakdA4gXm1CL1l7IBUI84jx0QZhAJc2BzyWc1l11knHczDF+P2BPv+R43Q92a7yTDkCXOJUuYYRu/OhPDrXJiN0D5t5iB9EJCgHMQpKkBx35DYkXGoYVZ2TbuiJMm9E6kU0npVizkZX9zuNzpYnMMH91EnaEUDT+nC6uLxXjVd0U3T+hBC6Is3UzWPsiTH9sKvwJt9WV1hg7RHORvl4yEdz30mufuHIzSi0CQsXliT+s7Wzpu3Pgdl1q714UOsjbzbgVM0iLND1udS3HJ+NywI8+G1MVyujXut4r+jb9Z3NUej0Te2uDs9b/0jBcM+4HSCBfgXbFZG+WHjiIgYxftzi2TSUMzPrOzqjYk7LbLoGNtCpWTnOdbbJO2EUw5Y2xWABSMm4EtYTi9GirLU15AXAEYRDGC7RFynhgKjKo6lFjAuL4RnIYbuMY2nmoNFL8JbuOpcI87lVl6Am+aCymxLGI7DoXSo3wDqIGNh/aYdPB/4ykFT1Jnok95NPJqvqL/szxh8nhCx0ngGiOarNFqsHVJXT8kBPQvK5JtGrZ+ieYStrOohiKeFEUmnUPFgzuWongCOmh8gY3pMjfsFl+2yFYrXXTHglwzZyRZ4gqgL+JyGKdC8GM2kGGQslHaxZ3yASs=
  - secure: mxynnvtb10U+q6uC/p+l7yzsGFSBPpTBWDB6n3Vx6uXHfKDwJxK4kzOrPJmzphG/7H6sbgyhSZkjzVeXK1hX/xTc+LeXeKzO30RH1qhznPz9Dr43QS8QURGwgRUxa92cmAyZARzdTYMylLti1gGR36Hu3iTmuTsBLXhqftorK47VOei1Yu7NiwG0Tv7JqtUdJuYAjCDI686HNzQ1iftknXLFFt8TVRI1YilHv32pTAP59sJplH39Cg2bQrNdqLs7xwAY5RCul+44xxKMaMYtuOwzwpj9XHFxiea1oOzC78Ky2cpj/QAmw3m+38seumDVProvYKsgYiT17E8GWqKctyXT4DByHj9U3dn2648FSBnV2D3c5iXIzMIwQL2ZCwrDA6SwUzZvdKA84ym5IOwj6b5XdXqoKrNSqaZXSBWJNxqbA4CFJUBCO0YY/GzRbMoespA9BHMc8iB7goR15tfJGVQl0x7u9F40uzGtxeYf32XpsWZWRc6zFzqKRpgI6O1Xkt5yEzDL+v2/i30zTrggg9o3GwLu3NuF6mTumAzQnCW47LfgYxs2PnBwmXgwMni/VvtLydfHfRncOJbGVfmVtC+JRVG6j++0VMrAQgYSUWobGLm/BREsGFrLv9oWcrHLZAxUBLKMB6Z/T8AluYBR7OAAPEs685pMHQv7e37KiI0=
  - secure: M0u8WzvdTXeCrEdaAaymrZq8XGwjO1SlAg7Km5/TQ2tZ5z36f0Xt9Xh+PHZqKdHLs6dsgAPidH/z4dcDCNVLR+SZtheI34jP+AEwnyMn/czNPaohMfrtY20+s+PQfkSidpGtFEF2J+ptajdunKXgwZ8x7qJY/5TkRBGiN9tLyUZ+jMav05KSWrebS2cw5wxulOx55WSZFLmkFuw8D7xDPxoL9EpGfUkn2dIXZ+fsoYbqq+vvoR0qeJe1u70IN5WBYoaK1SJA/2DOZbJ20sxbg2gFqRQyDiIO4Oju47kmGnogNtplWKTuKnPSHHIayjbWoyHBsMQEF/xYoV/qJxPqPyHmLJCxE4jMWwSncYnPlDGxHV8I5udm6WiakzQqzRwGpoCcteGW6xdP/f163sVQBM//kdMbwj+ntdld4yh4qb47Ekyxh8hSTIif2IG4f1vXMUPlDHpchqRfNY3AoxxVWKWaxdBY6DcZZ+jKKrJ8fyjrpU/eDAGYGmcNXvWn11xAbeF4hn8rpMEiMsD1twSGrt7IjeSZ0TgNfZe8QIDnHDhN8k3fdAz9sFRBsxrxefmcpwHHsJxpUCHPprgq/L8XJiyekGC8AORb8ZgNHMS+06NaA84FVx8ImRtqul1SNkGZqrkj8ALtm8qGAsUMx0NZaf+D45vh/zGSK9NrNMsKlg4=
