language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk: openjdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: g2CKr6/9ogKJS+raJM+KPtFAPjI9ToBlw+1sTTzsH+0ytpXZjegCp35i4+/B2MvMxkl8H1V+oa5QfAczhKNJ4U48t9DhibOchFrr8lgU9liH4G5bF4u8/mpBmU+0CgRbdT9SPiexlqOVKnXHeNXusV6mjxMM/S+0NF83MbtGBURmEItixQiC+91Dt894aCDX5qxm3Dpq5vBnlzQ95/rZyzLjtzJs8mZAWhoBaZNTXJng6dkTbP24QLuDyCynxY4Nz6SBbDhEZTsBbGKsnZ3Z5Grq83GachEDFudNJMV28YQwkq+7kCDqs76ndGCQnjkIIQqosMluh1xMeLSmvx4nGgdYmGOhc9pCPLJS+6/cPtiNsd10TdgIBxVPe7ApTSyDundYVGtG0RQRuHbIqValPW+GtcCGP23gkt3oAfLQIX+qhhN95eegopnJNyNQ0sOC9NTYU1yXy01XCqKJg2IsTQcR/Drv7Q6K8jCCX3Gmqn70ZBGw8/Tivm6eivKXJbbPP7Ix1LnJJzuw7abqGq/Nxtus3o9SyD9fm3WJS3pAqhHgarXd2Iod8kImwC+TDSMMBzDbzgACrKWvvI3K3WRvjvOOia4VpCXYM3Ctp8FlyRqmexwB0gZ2ceUJ1Sab4RNDPx1xEGqmJl/Zgz7cXuX3Auy6M1SJZCz2LtdmjGHf37I=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
before_install:
- sudo cat /proc/meminfo
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- chmod +x mvnw
jobs:
  include:
  - stage: build and publish to Docker Hub
    script:
    - travis_wait 15 ./mvnw package -Pnative -Dnative-image.docker-build=true -Dquarkus.profile=local
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and publish to Docker Hub
  if: branch = featBareMetal
env:
  global:
  - secure: jFo7VdOOpstTosS7lzeOCRlnRbC+RE29CJFwzom2eTryxx8nIL1fbSAyfLJhX46M/NtGOcQ+pdrRYbYJXmPlOlBtSZLyZU4TTscNRdL9B5JBh9yYpURZuk16gvHw7iKyYqMnXAAFKFPGx9Fb4sFItyegWrGsoW1E1X0ZPcJNPR+hZNnX1FPbYPD4fXC5tGP29nLS6zJ/6j03xgW0Xp00wcoZf3s4/O5k/IWNAKSqt8cGBJqhVP1xL3/qzGPYI2FmZls/VqsK6u36/jnKtr7S3+3PrbI+373WKDpxtMA2073jJcZdcQWRw8cXV1EVUWYdwZU6y/JMckQFMhY5rd7nHjDhhBwvMB7SgSG59PCNMRcBUQF5m4B0soiqkjEvb1NgotV2+iXuHok4hTJ9jNtNGHC0Cvlcoj4ey6YfnZLVGFfEI2N/ehSbgydqn22UbQmuIWvpLaOUG/64bVqXXsBTfgto3K1vb5RqvhidCdX93+FNTvpVuEnvlUwoeDAWJsHzzM2BpPfyJLR+B8XNB1aG/e/qObodACMEp2l4cprHA9PnhUY6A4uHYFdRwqfIpSVuZedMG7bKP2LNSUjXYlAIgDxmUw78xTm11xMjtpO3F/CtmU+BPZ7Qk+NAT2UVX5MIXaunhPCv8+3NZWKa44Oq5Oi6wGXrHtdwgLp9eEsogdI=
  - secure: YhpVwVDzsEOcTcpUevtEiaf4F91TSZbYtawR9X7bMqXSaaKM8BW/lza7sZdTHxBrixX8cVlVw0WN2NGWCz+xw6vruh5e8uPCve2z6sSdNOxK02SlLCzPP97CXX+F2hN8AVa1NgtE85T+hr/d9nIh4htOC9EnFrRpWAPh691fJwWZhawvu9bQnlif6lYliPKVN6bShqTRFS5iHj41/ggLlNPy32wM060dd/hxX/KojjYSBmPwykRI+CoszxKjL8KsIZuOWkYTZl7ajR8Fyu4+R95QGHhJHB4BVFPSlHGTN4qb62piDSvPuVU0v5ZEFssICmtZfZ0ZUNbNOOnunkMW6JnwuvUtfpUhc+R9BKo6AkxNCFHQImpYJFWnkOun8KoWlnAm8WAdNUufd/sdyiaRRy2wLRG6FXitlIAOWLnLile1NvJBS/wPmzxelPkcsTepfsuMQp8/+TZRgx3NnpzqDrSTMV2Syp9kyX8zn9x0gR5psH6p7hbY/W5L7qFfrjfxjhmKFEFiDG9HBPcpDm4xZ2ILYJJQotMRJl+XOXhNh954Yl/DV3C499QwUlF3he4ANUrh/o8QJOuLEhjTkzcXgEriJ7X4TbPch+9l7GuFrZ5ridtn6+csSqooS0Von1fZiix9a+Nf80XKZSoA67lN3nUz+rYncQa3HunV1JF4H90=
  - secure: Y68iEpLAsRaaeOv/tmwWGAEruszgqmJrVzhqwWni2BsEJTXlTwz9zakfY/GkKkAbYrpQpCHDkOO6cIos04ZXZw6Un7QDqTDIlLSJEYvXQYibN4jIQAfj0G0StOEYB0vLm/UF9xM+KLRvfmShwJYsAHy6Dok54i7BymRRG6c1e2m8s9TcLEig1/olkuQ2bqa620B7Yf9MASLN2v7PGxNY/RQ2DtDI1BJx2NtXtX7+/ZzgUSOMounpSfaoE71kVVI2ez4OQB/gt3RDpHZlhEX9SZXa0L9f2z6CFTWVAw8WtNc+D1ywv6w1zziNMCZkByaj2+dLMpaxCdyByT1Qgk8RM1pjSdnYqJDMpwrP85EiW0H6uNPaQY7KlDgF7MebfUupw9HAs+iajXF9zDOmEimt1PPjx2xplEGVOjlTXG+hH8FsiBuyi0hJdaNFjpsOHxTe8opzDJq3NaV1S63rY8EzvKHVJ4K39Z4nfeE8Yxq3pdJsT6xVou3nr5YJZ50CQ1/ERCQw/7LuW2JM8cANSJXoPM6HCPp2W2V96JKnddxbl/LZ6Gq6JPYQVXydZAjOKE8GY08ep8Qk2TFTBwpBAdJhU2Hk+Qaz4gXn7frlNUPfaiEQnSqfyy3PAkpuZD9WA9rbDJeUg8b6CgltihICLmM0DaCMTD4EZlRHjAsY6hjGeSg=
