language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: QR39qkn6R61iV+jpKsKdRzI66GnH0y5dyYbMLMCvaCCot1W5keXOaVlsxjeg05zA88AKUQ19Nlr5BUWeI7y2qsEvcyKd5obR5aosftGHXNsKf08Ozb1o5/XvuOApoYdXx0oC8V5DTKK+pEZ4z5aqYWLxGmA+Efp0L71iQVnUUBIu4lHm0NDfH3LTyrwixlP8pzByacS1hYjycFab36/sfQ3N6Y1/4nSOpuKAdKFzp5VOkKVhPKKuGe1Q8/XLGwvTcxHV3E/qGbmQ5bAVb+Jq26AcGoxVSsWiTqITEmWjMCCWwUzgMFoC04fIRN+ldK1LqnhM0ha6bsHTTbk+o8V++dyAfMEZsW47AKlUebtG8w5fFvLJhBGzl4R7n2vtjvUfgir06kqizq04egPf7kfahmdX89hyCoJuQvoqsGJlcBqrJyetSzsGypnxvswzvIzPB1eXf+PNiRJecNIrvLcEO1OBkxOFLe9lr9duzypoHFJy6+m9htjv+/PK/4Spds34iDp8CN+nSA3wpBfYccl4n5KpgUvtV6AgVEKks7CO1cEeG1Vb1H3W0ZEoDJ0yykd1Os7UYIdxxwSXeNuA18N0d5JoxlVv0SBYI1BdXMR4dUoDFiV05N0STGccqk0kFLpNgZM0OApRXcr3NmKb39H3MBc3OBa/LHNL6rYaptwQmFM=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: QPUfd4FA9DclMznVPAcxWXNZkWUcBE3V41RosKMWbQsJa5/QOsUDoCmnGDQQV0kfRZYSt9xzHbkR4/qjRAwPapn65g+zBtJvbgZXDZPBmibHq2KoTUXVL4Qhk/Pob6oJquRzfyWHqmMJZ1v3wIzPb51JdIvWTnp897Z065RhgGFuDf/e7cJk4Ub/qbdydmhR/8Tu9iMY6XlQCmqaztUKSemTy3+mJIt8QqpSfqyKBGcqsj4KGnznMQ0rOfXpXyBs1olhSCLsb+htKm+AcN0c3hRYXfafyA+5FkOfIXOoFMG4SonIcYooD1mwHb2rKCO0dw7FVwrF9rLR9l83mWyValDXDsUvTZDpF+4XkoGdK7YqTSQkzpLbzqx0AwwaZB6oRTCvZSm3HLuXTaEY9PlqTVD0wgepEhmZaaEekYcaqnMFFt0hcP6YLbZvPmVGY1cw4bknfQcYQGlYLBaETUS8JUTRBIXafjkuDwZSxAJ6IIOalh55rL/SgY6w6QozoYKtyigAn2/0O/zYKFVV5JQa1Bab58Kdyin+/nc4gRMZ4nfaMR1mg0DdhH5xFG2gmaDe4udEEXbBtYy+nllT94w+NejobFyocpqE6mYi1uiEI9mYW4qwDeiYg7ZCISD2MueX/pnx4wkWZBl000obxV0PIG3xyczR34uHJ7jYhFRN6fg=
  - secure: keGIgNOV//ll6vCakzlDf7Q7q8SXMKwRsrZTR3uJEYv4sh3udjHikHHowd31dxeWNm9OxgUPZq7/W3VXizvG/F2T8YtDNO6pMkm4rbWi/6If1Pvqdx/TwoSTKi5qFxjcxb0r5EA6xZCtO/7SRguJqY4m8vxocpWTn1/gTdkhfi9Ej0o47uq3VZiyeFoo8ENAmRQYk5NZH5aLIUmUcR3jbugwfsSPlROaoY7aF6uVn4Ttth03qBb3NPzyCsZNHB6IXpROJ4cbWvS72OlcNo3KATiyfYF3J1jvezS04QlsU0vQ/6wXtI0AYWcGoHzzFShj/7CSAR1prvBsSClGOLIR3oXb6AnAJo1+2z3qk3By/oqKxspUkWGk0BbCDms0CLceXl0l+BGdDhTtY344o3VMitMpTRWWw0QG1l6vaLK49XH8MZuQfQkw2OXJuv6fc86cC/cxI5U3+AwIjCZKjiqBOKutZcLU0nnb/k3Uuaf11vyw8FmrXSfjt3HDJ36pp/n1hRPfAgsQVd06pN5GCnhHmwAgh+lUW0mrPxfvXJCDpV11ClUWlV4uXoww/VVU63pWMIXQzdWiT7h8s4x3uOW79HsCX/9zdTsF3F6pqh8W4HGqx7WgAAFuIOZMjigEKkPB+yMBp0nGD2NIamMuZ5dsIjW5SfAnkuhFzL1RdWxnsag=
  - secure: Jyb9yPYTl5I1C+KR2bTORW/Jo4sX6W6Es8seB7V+MsBQC8ZF0jEAGQY2FD5Oso+d44IShFN7XqehC1BOHJlC/3t3yci/HdRNEwu2Czbj8kUDvC9+qqEz0p6KJgbKMManfGxa/O6CHq5EIvVCUGLOTOm+N4yIbpzUbA3LDp2Apb5XCwGGvJEE4p7aJ2e9Kqsjv+96Aaid9zbq7osr9UjyyMnmmDQdT47t/BZSMkoN2Yaw4xPY3LJzV23TtVDKg6MvpZ3hD9fG05qgUwoonb9sXW2bzaU5NxYsS6KMabAfxyn5SOdY1yGlRXvA7vHiU0m7UyCAlEB67ClMNzK0Xz4q9VnIzR/B9JXGcOOErr70H3OyyK8grbUcYiZ0NI6p16V4sCVetIh5tyBgslaI5jKi/XyT15gNqM9PHN5YqO2EF4nRdQzLliEBD9HrM+EsqU2e8Ab1pk+4G/sczUBq+1ISsHI42NZrhAFmDJu97fPWWv52esz8EvQDbYNSx7Exy6ulVyuG0DwHIDMjOPfEysaLcDSTxLJ2B0IZbeMwKD4CftXztHbmiN8WueAGOaPYl+d6dV6mbkAyxPPTPAWc96W66XCtw/IPOxB2zn7pZnUGw1ZZCWVD3FqqrcS8avyVOnW/VssMS8T5WJTUdbX6e7ucK6DqPF+o6Efbl7R57KsKLwc=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build and publish to Docker Hub
    env: GCP_ENV=re7
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and publish to Docker Hub
  if: branch = master
