language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk: openjdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: g2CKr6/9ogKJS+raJM+KPtFAPjI9ToBlw+1sTTzsH+0ytpXZjegCp35i4+/B2MvMxkl8H1V+oa5QfAczhKNJ4U48t9DhibOchFrr8lgU9liH4G5bF4u8/mpBmU+0CgRbdT9SPiexlqOVKnXHeNXusV6mjxMM/S+0NF83MbtGBURmEItixQiC+91Dt894aCDX5qxm3Dpq5vBnlzQ95/rZyzLjtzJs8mZAWhoBaZNTXJng6dkTbP24QLuDyCynxY4Nz6SBbDhEZTsBbGKsnZ3Z5Grq83GachEDFudNJMV28YQwkq+7kCDqs76ndGCQnjkIIQqosMluh1xMeLSmvx4nGgdYmGOhc9pCPLJS+6/cPtiNsd10TdgIBxVPe7ApTSyDundYVGtG0RQRuHbIqValPW+GtcCGP23gkt3oAfLQIX+qhhN95eegopnJNyNQ0sOC9NTYU1yXy01XCqKJg2IsTQcR/Drv7Q6K8jCCX3Gmqn70ZBGw8/Tivm6eivKXJbbPP7Ix1LnJJzuw7abqGq/Nxtus3o9SyD9fm3WJS3pAqhHgarXd2Iod8kImwC+TDSMMBzDbzgACrKWvvI3K3WRvjvOOia4VpCXYM3Ctp8FlyRqmexwB0gZ2ceUJ1Sab4RNDPx1xEGqmJl/Zgz7cXuX3Auy6M1SJZCz2LtdmjGHf37I=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
before_install:
- sudo cat /proc/meminfo
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- chmod +x mvnw
jobs:
  include:
  - stage: build and publish to Docker Hub
    script:
    - travis_wait 15 ./mvnw package -Pnative -Dnative-image.docker-build=true -Dquarkus.profile=local
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and publish to Docker Hub
  if: branch = featBareMetal
env:
  global:
  - secure: IqH5FjxXfcoSmDgguFljjqG+m8bTkPN/I6POj/rakj9A1Zai8eImgutfx2QuUXZWNvj3TBESE434P23tdohlL8L+Bffhmmuhz3sJEdFR56QVgEq6cSKA91siHNj1vCGy+AaxIiSECYLXhUzXN9UyaiRfs7ITrKMkXLXiywDL8cRP2sm1n0eWODeRJ5ZZGv4nM/dSPCB+hGEgSznPbezXm5X8K1PecD3eJXzxEQ9q1mWP8PcE2/ruzcQB6LdBaYDSifajAMrviciZ3yHNuAUujqhRK4+M/srGO90MiU0Iyb+7ZT985rEVLbh+tcfcLEyMvVNG5vJdO4PeihkqzY0ekPYW5knQl6mOTb3MnHJNXp+eqTdWjo2mNHq8Fhp4TJQekz+uFXupbK9XPwIAFnki9ld6JaBH57vqbk5b4xt07xNIjtqRQWZUjQj4mEznjEXfAdc8Atn/bUCUuTPx/moxJIEUJi3pAcfVQFaYowbShZ7DSORiRoxINWXyC+3XH2J/SSVFX71oTSTdVC6EWoO+M8hVRMphP/I5ebPjr6GkjRn/bhk1AwTR8KZj+VmC3uxdsUgUyZ6wHgFdkhGjK8I14ghzVxTd5QJQyXrOSOQzhiLBY78baRMBqygUUyEwf6e4QBM8h8rTKTzWoQlCcWQH8ulzsN63AxxBINx3V9lE4hE=
  - secure: vVUzd+5OoyLZZ0RmCNgMKyq+oEPl8DKI2ujbgYHEoofxFyNc1CL/90UsyQ++gWummcsCUQml8LTzAxyhsclDeBZxudOKrVAR5u8lTk54LiPigCfgjboAojpDDXP860XVYYzu/cTibJgeQBbeVOGOnQquOEU8DPpRmADgrDATOLz6WBQoAwLQRPtYxCocV3Ab1pbNvsTA1fQinPPRQPz/4MXLIkVzfsgtZmFzlydfAjY/jUaLQmDwL13GoNFfPOUcWX1gYjCnOCgGRyTPaw8AJ4e6kstl1kt94qPnqqdE5HvV1Etw2GjCw4qq+PiYhyy2tf7xjpAQ0qDbLHJdWFNkr1oNbeGw2s6rhXao5iw2dDDapaNgACKyVInRWAY/114inWbzQqPZQnwyosgH5aPAB0A9lDSVJ/7AkoISFb307g+K3k7D8UeEvZ9pdFINc+O19fiKsabe4KULziCcgSWc1u4qW27OQaVN3SaZgNAFWl19zX9uaXvbrHgsJWcCRPWD1rwT2hSG7JeHB6V1le1/w2Q6Uzz3j49DCI74FY4YH2HXRVLY7d5gtbnFV0/JFb6QCds/wtZAQx3/AR9DMkuaN0yXKdo87ikqCGr/aG1G5HcD2XeXwQXvdP9oeq62Bo4A0gjAwkOvHr1n558UYs9reXf+0sXiSsC59MHJjSYy2pk=
  - secure: UigPtbepL8d6U+1LKcToXy1Oz7XjA/wZgs5NkOxejJgdm6T5l09lFxEItB4BZfms8w/NMX0X1XLFpLnUoZAiel/ZdnLyhk/p+sroap0V+3YrOzsa+72KZsYUWXuxhy9Y2sTTAT/NX/ffJTg23FQdbVk0ZL1FjzBDSO1JkaK+pQzKQRoundW4UhWngk7vn7jSTgib0tSt59XtDz6dlubxgi4WX8kgXZmjkqTblw6vGhewdmbvzcam4NAV3ilaqxRc64omhyPFfJzKNtdcZmmdPf49p80PbxeHiMbQ2k77ZV/99ynZs8njmhP2z+8DLr46xh7zmAgQvJNDowkpyKrlHs+vdptip330PBomm+dbsngE2fs8/OlVjSLzFhD6vTJ7kCXVEG1+Rp6Ud0mviApznc/znY5v1ySmNlCiNMZAd4V9DFmezqfxBDehZXYxLX0lVn2j3AS0QJ/5Hp5Z7vrUq31uLousGZHuclMrRgTMLHegWJApCm9ERkWgAOPaIrrcCfjoNIhbXIQfvaJvPsX2l94cvTEwViNwSthsEh2rpp/JzuCShGB352rQOccRXfdmjPs7T+2FGD5oa8rba91bAIfBPnrdUam55AsSETZSAuEDzkOC/gbZWBA9ug0CLU02GAoN/95kdhwRphcZZ+FLGLbCAdppqmrsL4SBTYdewqE=
