language: java
cache:
  directories:
  - "$HOME/.m2"
jdk: openjdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: rZcBFZdhWdNy6Z4gR74WjdR1Zy5BdWCS0+s1J2/ATzgQihZkS5X6bmmJrhbiHil/UFQ/Gfe057HtWXEI2Tl3uGHMFuxc6zbU+/VNToYE7A91Pu2To5rsAUz2IIW/+B36l0W01ycScUfOCGdkKPuAhf3PO73tAVjbPVJv+Ztt56R/gCeHE+CcooUQcrEg+8ngPS5P+Ir7jJgvCX8oQm1bfuZmiAIDKEW5gsVAv7hglSZxY+5TgHw8ZvuJWUnTd2VXUWw5LUCIBPtT0d/1Z2JsYH9YpSPKtSrRLnQcMFF8msr3W1ODA47wai2YQVh9BlQkEckoaQWsvMM70JTXCWd0+DpipRqtRQtafixdxIwDEdoCiwRAgayHtvNNVuQvYywHfUmBiRK3xE8xvMOKw8cFa/iCNEOG6fkdz9SMOK5Zh+Ef7MykVyv4DJhj3pT09Fcc0/hfn/twqtyeqFPJVMrUfShGV137m8lXmIdjXnTF86YBgfJDemvtRgzY3f2wRXqCs6f03DccYsBsBxQJbxB4iKSnK/4PHPCka+DS5ZWgMNz7DSqogOILeoVOAcdRDeqtbu/91tPFdmOY17QbtdyQH+q29d/cRF4k0ati8r47xro3iHXCTtImIkiV7lVinZONtbEaUlrEjzHXk1PqL4vkavTEDYbdq+nwgh8uuKQa0LI=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: L6DbZWwPIwB9Q2K01gk1zPWdQjQOky/oRsMplt5JLPkp9FmovoKnbRmNBde0/jSZyyjqacs0mIVH5NoQlmAFLILN99XFoTBBNN1GmdtagzY4RE8vq20Re+iAI78heaYlcYa012zVRfLGTbLawYAuvWqtUBqrhhot2E5AYHegQ4LtSiKDmrd8/lK4tMn+zNC5WBHVxaQ0wCrLN3It0EmmX57MMlJO9WJFgzE3ZaIamEiHUXvJnDMJq8eZMTjSsdLIPTeMFTUsIib0YTSvZ0w1DjYS2+Cvsq5ZP0OwSqGPfMufYGS12MrwUb0nadFk3B0mrtO1cAjo2vhq6FHl4xEWR4sj88KHvQWFTlVetSYeKpIxgXosOcvjwoYWlevc00+DRQcW5FaU9cAwZU0Vm24MSiY3+AGo0hdeRi/jAauO7pOPHvPOWUb3GUA45r/NBXNmdHzjyY3q3vxnTL/9k40pNa7Tl20aNlnZdwHU0hDmw3LEKJXGKfWXcPPioZMxE/tZwC3HCx8C+NlcbU+wKpVjuR49kGgtjOd7cBX0rLmFAI8Kljua0srVuWfsCceZ9hpeapHxfmAjy8Lhs3O/R9e4UtKDoelIhKXWNxepFDCEQfv7Iq2H7TF2rSoKQdAndB3b5bx7y8536EDumidNqATg1rrRAi1Jj0AEQ9OKSOo04ug=
  - secure: Ufg30wUjKaK+PFygrsKvulC0amJm67CLRooWGYP0OR97RsQkBrfjrXlkH0rfD7QCaroC6klbcU+M6BfiX1Q2EBA6KRpctslueuzY3dHLe4RoapZK3fJlgtMgWyxooykTJPl40kCQq7z2L95KuKDk0j5t9YnhQ1tNWqxkfwIbsGYqgMP2hDqFcQ1zxjOiqb1auMMclNyxlrzQHGJ05pq7k4VO7f45v4vGwTX9GFr6FBCxvN+I9MQECLW/GdNlamiNsTia1jIUqbI2whKPBU2I/obzY4I1tqKB839/jon2Jon2jYdbP/VfrDxiB0bmOx7qhXn6KGHaHhLhvRvoDrMDuMPdmokEhhZyYcOXAPc+FynBWAPDAsiPAJ3FDf1jh9DWgyUlQgfQBBO3K6WNXBtmfpYb4TR74L4ByV5rvPetQy8hgB2BpLpEzHg95/O/yEtcAJ7MS4vSvVdmis2Hll1Dghs2RIXqM0uiPJ8gKK7n4ibuUuJ5gsMtcEwiaOjI5fu0y5v6xWZqtYwiU34tbUQXr9mqwDq5tUz+PkVToVdJo5Hj072aU6VadaE5qM4ZQoaSLK78FrBUumuaXBsHbKevaYzWTPyr7w3COxup/jC9iMzhg+zjXPWGFNRavCzWm+bdIbAEcta/IycB8l7SCdkS73zdz5BGAGS0eTN1diHoYkg=
  - secure: DhTbZW6d8ogtdn9RbaN00BFvQrmo4V8bm4oNgOZrA7hgL1NtgxwPYyGfq5weDiCmWORoxP5RjmiWM1MnryfIuzVzOTVfh55XN9IhRULsbfuai6pwfkmqbS0XneBHLkytFjHK0SeKA/kAUseWEhuW72LjZBo9eZtxETFcfgiPmUDOUDiotfJT+RRXOy30WQMYHw/2bEyJD5eubEGeDC48avo/4xpwwXdbaI1bptvvaklfp3/0eIt33krvLq8RVmJmG8g9SQU+qYEaHVYb1I5j9lLVrR9mx7Cjc3V9CMXF1Nevg1DljIBbM/j7GpMeOtO0QJXTCE+IcBNXLTaHzDF8uP6qrwM3kuBTqdfV+UywT2OUurLBEgDw2lzr6dHEAX6ZZAa+PLt+cCwB66r84PnkFLIaCRns0D27O6bA5eZJfeC4coJfXCoPzjbGgicmXS/V/Ge1yxz2FbsYe8UOsJCr+HQxTwm6X4luOT+9gN9HZjwMDciNiorQ9JLFMLBGJDAEkL0UPiLrNSQRclt9LAvaRJprUKjaffDub45hZeodkQBKB89y3dXW6mA5Aw++lgPyvRfKOwajMwdiMVdiJwH3tpF3fo+gqCYgRYbzOE2fxlBhv7dfz6PHgtZLsOScBANbrVuXT+2EMSgrvtGbCBDuNaVKKbheG6fDo7V2DbpE+5s=
before_install:
- sudo cat /proc/meminfo
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- chmod +x mvnw
jobs:
  include:
  - stage: build and publish to Docker Hub
    script:
    - sh scripts/travis/tag_build.sh
stages:
- name: build and publish to Docker Hub
  if: branch = featBareMetal
