language: java
cache:
  directories:
  - "$HOME/.m2"
dist: trusty
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: L3/IgdSmP7SLV5zwHqXievCeeH1eNa9QHgIHz20bo2/RcE9nZpADTG52ZYwA29KpmxBeE6KlwTFvM9OK5Rg/ZhKMc+A3oTYMbBpWbOicZxS/nUXKNfxywdlKmOs2wce/bR524DoTsE8Rg0723tLMEqwRxw2Q5pgg6YPiF8xS/xCVqVAaYHpoil9YDyDfgNMSJJI02I7y4ETyVph0dlHKRdnBRrDjIOfVOa6udyiIhDyiKQr7TVxkhF3fwXwH5/WbqS5eaV4FTvvkeizWitRTNtbG7pgB2ikIqFOn7Fp+8XQrcHNPawTb2ozgbdeyF4Ks3NHw0U32JE9+w36eWiLhehbrZRgu1jSsjj4pvuzmyt8QvAvJUOwp2Y+PzeuFENnPf+fJUMH25rrul45aDbgIOcreEKQWmLM121GczEyLRWan4xl7UeanQrKDv85QqAYiYaCtY//9StKRWPOi5qfshjxd1yAAAefSG8UqCrwdbqKAwjcOFmEERibqUQbwLxtR127fUhzvtodQbSljN5knQ1/nHtX1iR/TK8dhRYRP0HZvwlr+ORk3ZH3tMc0ro6vA3Wqwizw0zXitygyXxU5yok+6K7YYzzehoOINVvFeK2TKl8GvLfIhw1bMug0Tr1ClJCQdU9B7R1x43nIicYw68ClOKbSIDUqPhFyRg3f8ceQ=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: NjObo7TmkcQ7s8r8kTy5mocDaQP3+lcrvv/J+UVQsGLSMOe7K6fM3a8ip0bE4QfUDoLwq4CHKH/ngZqXxznUns7BbaN+Ox9HW1RUznwb6+1Nz8X05q1YaVwI6ZP+FzhCyzp4+lP5bqmOsU7d8XMQSDB9JPrHx2BAQkde7byqM/gwtEDdw0BVUE1emcCPfWh1hKPl+rYP4mU1tQiO7Xvsx9nMBVJaKm1UJR29i6Df3+ITCwoPyWuAg9UKW9ZvPV4FzPddA74sJAlGg44U9BAweEmjxRwAUOBdENzB1DDaXRszUZAJebd8maCHysvVLy2NiTR4e+SYFcw+qjSPmdhC9laOK/BsY9OxIZMFqkZZH/l0yxtwnRff8olDnO4Vks1Dqpw70A1/FllACVUZ5o9cB9BmFgMprNTJRlt7M522ueeekuHfbFiPOxb/ckBex6Dt7CkLLnbmWaxx7OoIJBKVb8GbOwSSt+2vMbeL9QbfIm2jG3y90BYMtRs66MJq0rnGq12wWEbv9AMj4+yWOnYkXsaQzyMKe6y30SWNdNkFxgp5mOn3OEfZSwq3OhxDgKWnRHzAdiQJcxksrmt/FZD8lRQslie1+cPrNjVEqtbwmRQ4knaZ7zOfZIZj13XUhrJl0GOGFUSK4X9CAKIB08bZ5QBWOQ7ctS65FFF84VaXn7Q=
  - secure: eoHjHw77LujgSPypk1rWvyxh6Z+TwBQ9iAdANq2BxKYX4n6z6KCIa5EAetJObR4OqbVqy+ZrGIFLNg8oPYSO2Wu/998gSyZymOKex9Ll10BaM6OsKijmfCgBN9uGqfuK0xInCYoIBsnHttglNg0ke9TbSRRFwBa3b5EbzkdABBlYyo4V1yOHlZ7DPSTwfvwzdoXJfbMLxNM1BNAO/lv6MMbIJCZ9tfRadn3j4PwIWuQWWFu0D0TOpxHP8PgJ/5z/P+HNhwKRdYkCgp8yC4udZi7mhPZPiB2j3B51ZUZax5ZGsl9Xpsa+VcFa34trAusaty5sGBHQ00jEwT57ZmSdhHOzuSk5xM7tyT5dvypWJPZp7e+Jf+O7zwQGcuvQJKzJIKQwrYlmkPQx2lSXnDzMzgcexys3W901Sgy03Ez1UNiB/r11oI6xW91PMWxK0le6BSf5KGU0jaiw7e0Nk0eIW/+mjoChvhEm8NZZmwElaR6PMPtyqBzrzP6Uf8ZBLL9FHWoHKJ03lXlkAVs4XySCQE9Qdr+bfCRwBqZXigR2NI2Pgbu8/OV6KU9zaVMarvd/w85FcHxIq7ADTXDybdYpM4WW+tU0bSsVhEUz3CwSdm+/dyyz2l92UfsH7ugHVn4GLmZE9Y/jzi6QrXxOA/bYw9GFb7ClAg6t0FFXx+b9T0A=
  - secure: Lzniw+8KmQla1Je8P10YKKhEYO7CVlMBrGQC2wuX8QBRFOqd+FsNalNqQkff5JjVf3j2I8KOM406JupySk4QqLL7Fl9Idnk/BrvupcqWWQZFHssypy0SBC4SxR2qa/ii3PIkkP9urO2z46mqHDCsqs68bE1187CbXk/8mpACe+hOgVzzA+NpqCvQphYCEze8IseGE9Q6Eq3R8Ma9nyDJR165mG+ZN93D7U/utFuVEClxueJ/MwkgoSR4+GZGiw/eNkPpTdH0BZn94VPCKCPDF4M5dN2C7RozRDCBBzakhtlCSkkdvCRdFtJal3NPCyUwrZXjuSZHPHrBXyQU1Gx1NWpfc4lWtFX8rzxhfL9A2YswvczXsR1xMdIf1BvUQdGzdfVKuEiK/wpTclbfnRoCyrLzNdW2e0sdIgFqwmOkAkROVFvUTV9/UnKay4UdYkZhZl/3SoVfZdJYgGpyfLS/2ha0Zw4Ns57xxhMpKJhyU9CzD3tFOe3YIJnrnVfcjkYo1UEggm7+xr0e59h/ntbLxhktHUjn59snRi1CC1us5tUeYDiojyJiHWE+omY88qHcVhQRliRa5u3X8aR1IM28urw7SbOxw7OoeUfYFbqnedtmtalGubA1czKPkyqgdq9tWZetRAqUIgn37EOzYQiXDArDJoXgeyaS3JUnERpl9EY=
before_install:
- ruby -v
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-pedigree-service-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
jobs:
  include:
  - stage: build and publish to Docker Hub
    env: GCP_ENV=re7
    script:
    - sh scripts/travis/tag_build.sh
    - sh scripts/travis/build_services.sh
    - sh scripts/travis/deploy_to_docker_hub.sh
stages:
- name: build and publish to Docker Hub
  if: branch = master
