#Fichier de config CloudBuild
steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
# Get credentials
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=ws-openid-enc > ws-openid.json' ]  
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-f', 'src/main/docker/Dockerfile.multistage', '-t', 'gcr.io/$PROJECT_ID/pedigree-service:$BRANCH_NAME', '.' ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/pedigree-service:$BRANCH_NAME']
# Deal with branch master and write to file /workspace/_ENVT
#- name: 'ubuntu'
#  id: 'Setup'
#  args: ['bash', '-c', "echo `if [ 'master' == '${BRANCH_NAME}' ]; then echo 'prod'; else echo '${BRANCH_NAME}'; fi` > _ENVT; echo $(cat _ENVT)"]
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${BRANCH_NAME}-ws-pedigree-service', '--image', 'gcr.io/$PROJECT_ID/pedigree-service:$BRANCH_NAME', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
#  args: ['run', 'deploy', '$(cat _ENVT)-ws-pedigree-service', '--image', 'gcr.io/$PROJECT_ID/pedigree-service:$COMMIT_SHA', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/pedigree-service:$BRANCH_NAME'
options:
 machineType: 'N1_HIGHCPU_8'
 diskSizeGb: 200